spring.application.name=employee-attendance-leave-system

# ???????
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/attendance_system?useSSL=false&serverTimezone=Asia/Taipei&characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=123456

# MyBatis ??
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.employee_attendance_leave_system.model
mybatis.configuration.map-underscore-to-camel-case=true

server.port=8080



